2 dice
zknone/javascript_edvance pull request #2
Opened 2024-01-09 18:14 UTC by zknone

2024-01-22 17:20 UTC, Levitinn requested changes

2024-01-22 17:20 UTC, Levitinn commented on app.js
решение отличное, но нужна проверка, если в  throwDice передано некорректное значение, например d3 или что угодно еще

2024-01-23 12:23 UTC, zknone commented
@Levitinn  добавил проверку

2024-01-23 18:14 UTC, Levitinn approved these changes

2024-02-27 16:57 UTC, merged