3 birthday
zknone/javascript_edvance pull request #3
Opened 2024-01-19 16:00 UTC by zknone

2024-01-22 17:24 UTC, Levitinn requested changes
2005/1/22 не пропускает, а вот 2005/1 - пропускает. нужно поправить

2024-01-23 12:19 UTC, zknone commented
@Levitinn поправил

2024-01-23 18:15 UTC, Levitinn requested changes
2006/0/0 принимает, а не должно

2024-01-26 16:23 UTC, zknone commented
Пофиксил!

2024-01-27 19:15 UTC, Levitinn approved these changes

2024-02-27 16:58 UTC, merged